getgenv().supported= {
    [3623096087] = "https://raw.githubusercontent.com/silencedevs/SilenceScripts/main/Scripts/MuscleLegends/Loader.luau", -- Muscle Legends
    [75992362647444] = "https://raw.githubusercontent.com/silencedevs/SilenceScripts/refs/heads/main/Scripts/tapsim.luau", -- Tap Simulator
    [88933961678687] = "https://raw.githubusercontent.com/silencedevs/SilenceScripts/refs/heads/main/Scripts/HyperSpeedRunner.luau", -- Hyper Speed runner
    [95082159892680] = "https://raw.githubusercontent.com/silencedevs/SilenceScripts/refs/heads/main/Scripts/%2B1SpeedKeyBoardEscape.luau", -- +1 Speed Keyboard Escape
    [142823291] = "https://raw.githubusercontent.com/silencedevs/SilenceScripts/refs/heads/main/Scripts/mm2.luau", -- mm2
    [114204398207377] = "https://raw.githubusercontent.com/silencedevs/SilenceScripts/refs/heads/main/Scripts/SurviveZombieArena.luau" -- survive zombie arena
}
