getgenv().supported= {
    [3623096087] = "https://raw.githubusercontent.com/silencedevs/SilenceScripts/main/Scripts/MuscleLegendsLoader.luau", -- Muscle Legends
    [75992362647444] = "https://raw.githubusercontent.com/silencedevs/SilenceScripts/refs/heads/main/Scripts/tapsim.luau" -- Tap Simulator
    [88933961678687] = "https://raw.githubusercontent.com/silencedevs/SilenceScripts/refs/heads/main/Scripts/HyperSpeedRunner.luau" -- Hyper Speed runner
}
